cate/article/urls.py
from django.conf.urls import url
from article import views

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^article_list/$', views.article_list, name='article_list'),
]

cate/cate/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import product.urls, product.views
import article.urls
import contact.urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', product.views.index),
    url(r'^product/', include(product.urls, namespace='product')),
    url(r'^article/', include(article.urls, namespace='article')),
    url(r'^contact/', include(contact.urls, namespace='contact')),
]

cate/contact/urls.py
from django.conf.urls import url
from contact import views

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
]

cate/product/urls.py
from django.conf.urls import url
from product import views

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^product_list/$', views.product_list, name='product_list'),
    url(r'^about/$', views.about, name='about'),
]

cate/contact/models.py
from django.db import models

# Create your models here.

cate/product/models.py
from django.db import models
from common.basemodel import BaseModel


# Create your models here.

class ProductManager(models.Manager):

    def __init__(self):
        super(ProductManager, self).__init__()

    def get_new_food(self):
        """返回最近更新过的美食"""
        return self.all().order_by('-update_time')[:6]

    def higher_rate(self):
        return self.all().order_by('-click_rate')[:9]

    class Meta(object):
        abstract = True


class BannerManager(models.Manager):
    '''横幅广告管理器'''
    def get_new_banner(self):
        return self.all().order_by('-update_time')[:3]


class ProductModel(BaseModel):
    '''美食模型'''
    # 美食中文名
    zh_name = models.CharField(max_length=30)
    # 美食英文名
    en_name = models.CharField(max_length=30, null=True)
    # 美食图片
    image = models.ImageField()
    # 美食价格
    price = models.IntegerField()
    # 美食点击量
    click_rate = models.IntegerField(default=0)

    objects = ProductManager()

    class Meta(object):
        db_table = 'product'


class BannerModel(BaseModel):
    '''横幅广告模型'''
    ad_name = models.CharField(max_length=30)
    ad_image = models.ImageField()

    objects = BannerManager()

    class Meta(object):
        db_table = 'banner'

cate/article/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'article/article.html', locals())


def article_list(request):
    return render(request, 'article/article_list_content.html', locals())

cate/contact/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'contact/contact.html', locals())

cate/product/views.py
from django.shortcuts import render
from product.models import ProductModel, BannerModel
from django.core.paginator import Paginator
from common.pack_original import get_param
# Create your views here.

def index(request):
    # 取出最新更新的美食
    new_list = ProductModel.objects.get_new_food()
    # 取出点击量较多的美食
    higher_rate_list = ProductModel.objects.higher_rate()
    # 取出最新的广告横幅
    new_banner_list = BannerModel.objects.get_new_banner()
    return render(request, 'product/index.html', locals())


def  product_list(request):
    prod_list = ProductModel.objects.all()
    # 分页显示所有商品
    page_num = get_param(request, 'page')
    num = 6  # 每一页显示美食个数
    paginator = Paginator(prod_list, num)
    page = paginator.page(page_num)
    # 推荐商品
    new_list = ProductModel.objects.get_new_food()
    higher_rate_list = ProductModel.objects.higher_rate()
    new_banner_list = BannerModel.objects.get_new_banner()

    return render(request, 'product/productlist.html', locals())


def about(request):
    return render(request, 'product/about.html', locals())

cate/templates/about.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>美食城网站模板-模板之家cssmoban.com</title>
    <link rel="stylesheet" href="../../../pro2/default.css">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7"/>
<meta name="format-detection" content="telephone=no">
<meta name="renderer" content="webkit">
<meta name="author" content="www.cssmoban.com" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Cache-Control" content="no-siteapp" />
<meta name="description" content="" />
<meta name="keywords" content="" />
<link rel="stylesheet" href="{% static 'default.css' %}">

    <style type="text/css">
        html, body {
            margin: 0;
            padding: 0;
        }

        .iw_poi_title {
            color: #CC5522;
            font-size: 14px;
            font-weight: bold;
            overflow: hidden;
            padding-right: 13px;
            white-space: nowrap
        }

        .iw_poi_content {
            font: 12px arial, sans-serif;
            overflow: visible;
            padding-top: 4px;
            white-space: -moz-pre-wrap;
            word-wrap: break-word
        }

    </style>
    <script type="text/javascript" src="http://api.map.baidu.com/api?key=&v=1.1&services=true"></script>

</head>
<body>

{% include 'common/header.html' %}

<main>
    <div class="main-head">
        <p><span>关于我们</span></p>
    </div>
</main>
<div class="main-all-width">
    <div class="main-about-body">
        <div><img src="images/about1.jpg"></div>
        <div><img src="images/about2.jpg"></div>
    </div>
    <div class="main-about-footer">
        <p class="chinese">公司致力于帮助传统行业实现在互联网时代的转型升级。目前经营的范围包括：电子商务平台开发技术支持、技术转让、运维技术服务、大数据、云计算等。</p>
        <p class="english">The company is committed to help the traditional industries to achieve the transformation and
            upgrading in the Internet age. At present, the scope of business includes: e-commerce platform development,
            technical support, technology transfer, operation and maintenance, technical services, big data, cloud
            computing, etc..</p>
    </div>
</div>

<main>
    <div class="main-head">
        <p><span>我们提供</span></p>
    </div>
    <div class="main-we-provide">
        <ul>
            <li><span><img src="images/lunch.png" alt=""></span>
                <h2>中餐</h2>
                <p>公司目前经营的范围包括：电子商务平台开发技术支持、技术转让、运维技术服务大数据、云计算等。</p></li>
            <li><span><img src="images/dinner.png" alt=""></span>
                <h2>晚餐</h2>
                <p>公司目前经营的范围包括：电子商务平台开发技术支持、技术转让、运维技术服务大数据、云计算等。</p></li>
            <li><span><img src="images/coffee.png" alt=""></span>
                <h2>甜品/咖啡</h2>
                <p>公司目前经营的范围包括：电子商务平台开发技术支持、技术转让、运维技术服务大数据、云计算等。</p></li>
        </ul>
    </div>
</main>


<main>
    <div class="main-head">
        <p><span>团队成员</span></p>
    </div>
    <div class="main-team">
        <ul>
            <li><span><img src="images/team1.jpg" alt=""></span>
                <h2>大卫</h2>
                <h3>厨房主管1</h3>
                <p>我们始终秉着严谨认真的专业态度，为顾客提供最棒的服务。</p></li>
            <li class="main-team-display"><span><img src="images/team2.jpg" alt=""></span>
                <h2>米娜</h2>
                <h3>厨房主管2</h3>
                <p>我们始终秉着严谨认真的专业态度，为顾客提供最棒的服务。</p></li>
            <li><span><img src="images/team3.jpg" alt=""></span>
                <h2>大卫</h2>
                <h3>厨房主管3</h3>
                <p>我们始终秉着严谨认真的专业态度，为顾客提供最棒的服务。</p></li>
        </ul>
        <span class="prevbtn"></span>
        <span class="nextbtn"></span>
    </div>
</main>


<main>
    <div class="main-head">
        <p><span>联系我们</span></p>
    </div>
</main>

<div class="main-all-width">
    <div class="main-about-body main-padding">
        <div class="main-about-map">
            <div style="border:#ccc solid 1px;" id="dituContent"></div>
        </div>
        <div class="main-about-info-right">
            <ul class="main-about-info">
                <li><span></span>
                    <p>大冶大道江浙商贸城金穗小区好太太办公室</p></li>
                <li><span></span>
                    <p>0714-8868331</p></li>
                <li><span></span>
                    <div class="date-box">
                        <div class="main-about-datetime">
                            <div class="main-about-date">周一至周五</div>
                            <div class="main-about-time">
                                <div>中午11:00-12:00</div>
                                <div>下午17:00-22:00</div>
                            </div>
                        </div>
                        <div class="main-about-datetime">
                            <div class="main-about-date">周一至周五</div>
                            <div class="main-about-time">
                                <div>中午11:00-12:00</div>
                                <div>下午17:00-22:00</div>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

<main>
    <div class="main-head">
        <p><span>在线预定</span></p>
    </div>
    <div class="main-reserve">
        <form action="#" method="post" id="food-reserve">
            <ul>
                <li>
                    <label for="username">姓名</label>
                    <input type="text" name="username" id="username">
                </li>
                <li>
                    <label for="phonenumber">电话号码</label>
                    <input type="text" name="phonenumber" id="phonenumber">
                </li>
                <li>
                    <label for="email">电子邮件</label>
                    <input type="text" name="email" id="email">
                </li>
                <li>
                    <label for="time">时间</label>
                    <input type="text" name="time" id="time">
                </li>
                <li>
                    <label for="numberofpeople">人数</label>
                    <input type="text" name="numberofpeople" id="numberofpeople">
                </li>
                <li>
                    <label for="date">日期</label>
                    <input type="text" name="date" id="date">
                </li>
                <li>
                    <label for="guestbook">留言</label>
                    <input type="text" name="guestbook" id="guestbook">
                </li>
            </ul>
            <a class="reserve">预定</a>

        </form>
    </div>


</main>


{% include 'common/footer.html' %}

</body>

<script type="text/javascript">
    //创建和初始化地图函数：
    function initMap() {
        createMap();//创建地图
        setMapEvent();//设置地图事件
        addMapControl();//向地图添加控件
        addMarker();//向地图中添加marker
    }

    //创建地图函数：
    function createMap() {
        var map = new BMap.Map("dituContent");//在百度地图容器中创建一个地图
        var point = new BMap.Point(114.973831, 30.107665);//定义一个中心点坐标
        map.centerAndZoom(point, 18);//设定地图的中心点和坐标并将地图显示在地图容器中
        window.map = map;//将map变量存储在全局
    }

    //地图事件设置函数：
    function setMapEvent() {
        map.enableDragging();//启用地图拖拽事件，默认启用(可不写)
        map.enableScrollWheelZoom();//启用地图滚轮放大缩小
        map.enableDoubleClickZoom();//启用鼠标双击放大，默认启用(可不写)
        map.enableKeyboard();//启用键盘上下左右键移动地图
    }

    //地图控件添加函数：
    function addMapControl() {
        //向地图中添加缩放控件
        var ctrl_nav = new BMap.NavigationControl({anchor: BMAP_ANCHOR_TOP_LEFT, type: BMAP_NAVIGATION_CONTROL_LARGE});
        map.addControl(ctrl_nav);

    }

    //标注点数组
    var markerArr = [{
        title: "大冶云阿拉丁",
        content: "我的备注",
        point: "114.973835|30.107743",
        isOpen: 0,
        icon: {w: 21, h: 21, l: 0, t: 0, x: 6, lb: 5}
    }
    ];
    //创建marker
    function addMarker() {
        for (var i = 0; i < markerArr.length; i++) {
            var json = markerArr[i];
            var p0 = json.point.split("|")[0];
            var p1 = json.point.split("|")[1];
            var point = new BMap.Point(p0, p1);
            var iconImg = createIcon(json.icon);
            var marker = new BMap.Marker(point, {icon: iconImg});
            var iw = createInfoWindow(i);
            var label = new BMap.Label(json.title, {"offset": new BMap.Size(json.icon.lb - json.icon.x + 10, -20)});
            marker.setLabel(label);
            map.addOverlay(marker);
            label.setStyle({
                borderColor: "#808080",
                color: "#333",
                cursor: "pointer"
            });

            (function () {
                var index = i;
                var _iw = createInfoWindow(i);
                var _marker = marker;
                _marker.addEventListener("click", function () {
                    this.openInfoWindow(_iw);
                });
                _iw.addEventListener("open", function () {
                    _marker.getLabel().hide();
                })
                _iw.addEventListener("close", function () {
                    _marker.getLabel().show();
                })
                label.addEventListener("click", function () {
                    _marker.openInfoWindow(_iw);
                })
                if (!!json.isOpen) {
                    label.hide();
                    _marker.openInfoWindow(_iw);
                }
            })()
        }
    }
    //创建InfoWindow
    function createInfoWindow(i) {
        var json = markerArr[i];
        var iw = new BMap.InfoWindow("<b class='iw_poi_title' title='" + json.title + "'>" + json.title + "</b><div class='iw_poi_content'>" + json.content + "</div>");
        return iw;
    }
    //创建一个Icon
    function createIcon(json) {
        var icon = new BMap.Icon("images/position.png", new BMap.Size(json.w, json.h), {
            imageOffset: new BMap.Size(-json.l, -json.t),
            infoWindowOffset: new BMap.Size(json.lb + 5, 1),
            offset: new BMap.Size(json.x, json.h)
        })
        return icon;
    }

    initMap();//创建和初始化地图
</script>

<script src="lib/jquery/jquery.js"></script>
<script src="lib/bootstrap/bootstrap.js"></script>
<script src="js/main.js"></script>
</html>

cate/templates/article/article.html
{% extends 'common/base.html' %}

{% block title %}
    <title>资讯</title>
{% endblock title %}



{% block main %}
<main>
    <div>
        <div class="main-head">
            <p><span>美食资讯</span></p>
        </div>
    </div>
    <ul class="main-submenu main-submenu-second">
        <li><a href="#">最新新闻</a></li>
        <li><a href="#">餐厅新闻</a></li>
        <li><a href="#">美食热闻</a></li>
        <li><a href="#">甜品站</a></li>
    </ul>
    <div class="article-list-banner"><img src="images/foodnews1.jpg"></div>
    <ul class="article-list">
        <li>
            <div class="article-date">
                <strong>06</strong>
                <p>2017-06-01</p>

            </div>
            <div class="article-info">
                <a href="article_list_content.html">
                    <h3>一大波餐饮大咖正在分享经营经验，你需要的都在这里！</h3>
                    <p>大多数老餐饮人都有一种感觉，那就是近几年像原来那样按部就班地赚钱好像越来越难了，行业里的“套路”越来越深。行业竞争...</p>
                </a>
            </div>
        </li>

        <li>
            <div class="article-date">
                <strong>06</strong>
                <p>2017-06-01</p>
            </div>
            <div class="article-info">
                <a href="article_list_content.html">
                    <h3>一大波餐饮大咖正在分享经营经验，你需要的都在这里！</h3>
                    <p>大多数老餐饮人都有一种感觉，那就是近几年像原来那样按部就班地赚钱好像越来越难了，行业里的“套路”越来越深。行业竞争...</p>
                </a>
            </div>
        </li>
        <li>
            <div class="article-date">
                <strong>06</strong>
                <p>2017-06-01</p>
            </div>
            <div class="article-info">
                <a href="article_list_content.html">
                    <h3>一大波餐饮大咖正在分享经营经验，你需要的都在这里！</h3>
                    <p>大多数老餐饮人都有一种感觉，那就是近几年像原来那样按部就班地赚钱好像越来越难了，行业里的“套路”越来越深。行业竞争...</p>
                </a>
            </div>
        </li>
        <li>
            <div class="article-date">
                <strong>06</strong>
                <p>2017-06-01</p>
            </div>
            <div class="article-info">
                <a href="article_list_content.html">
                    <h3>一大波餐饮大咖正在分享经营经验，你需要的都在这里！</h3>
                    <p>大多数老餐饮人都有一种感觉，那就是近几年像原来那样按部就班地赚钱好像越来越难了，行业里的“套路”越来越深。行业竞争...</p>
                </a>
            </div>
        </li>
        <li>
            <div class="article-date">
                <strong>06</strong>
                <p>2017-06-01</p>
            </div>
            <div class="article-info">
                <a href="article_list_content.html">
                    <h3>一大波餐饮大咖正在分享经营经验，你需要的都在这里！</h3>
                    <p>大多数老餐饮人都有一种感觉，那就是近几年像原来那样按部就班地赚钱好像越来越难了，行业里的“套路”越来越深。行业竞争...</p>
                </a>
            </div>
        </li>
        <li>
            <div class="article-date">
                <strong>06</strong>
                <p>2017-06-01</p>
            </div>
            <div class="article-info">
                <a href="article_list_content.html">
                    <h3>一大波餐饮大咖正在分享经营经验，你需要的都在这里！</h3>
                    <p>大多数老餐饮人都有一种感觉，那就是近几年像原来那样按部就班地赚钱好像越来越难了，行业里的“套路”越来越深。行业竞争...</p>
                </a>
            </div>
        </li>
    </ul>
    <section class="article-btn">
        <span class="article-prev-btn"></span>
        <span class="article-next-btn"></span>
    </section>
    <nav aria-label="Page navigation" class="article-page">
        <ul class="pagination">
            <li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li>
                <a href="#" aria-label="Next">
                    <span aria-hidden="true">下一页</span>
                </a>
            </li>
        </ul>
    </nav>
</main>

{% endblock mian %}

cate/templates/product/index.html

{% extends 'common/base.html' %}
{% load staticfiles %}

{% block title %}
    <title>美食之家</title>
{% endblock title %}

{% block main %}
<main class="main-first-bgcolor">
    <div>
        <div class="main-head">
            <p>
                <span>我们提供</span>
            </p>
        </div>
        <div class="main-we-provide">
            <ul>
                <li><span><img src="{% static 'images/lunch.png' %}" alt=""></span>
                    <h2>中餐</h2>
                    <p>公司目前经营的范围包括：电子商务平台开发技术支持、技术转让、运维技术服务大数据、云计算等。</p></li>
                <li><span><img src="{% static 'images/dinner.png' %}" alt=""></span>
                    <h2>晚餐</h2>
                    <p>公司目前经营的范围包括：电子商务平台开发技术支持、技术转让、运维技术服务大数据、云计算等。</p></li>
                <li><span><img src="{% static 'images/coffee.png' %}" alt=""></span>
                    <h2>甜品/咖啡</h2>
                    <p>公司目前经营的范围包括：电子商务平台开发技术支持、技术转让、运维技术服务大数据、云计算等。</p></li>
            </ul>
        </div>
    </div>

    <div>
        <div class="main-head">
            <p>
                <span>菜式欣赏</span>
            </p>
        </div>
    </div>
</main>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/" >网页模板</a></div>
<main>
    <img class="mdbanner" src="{% static 'images/mdbanner.jpg' %}">
</main>
<main>
    <div class="main-body">
        <p><span>每一种食物来源都经过我们的精挑细选，关于食材我们只选最天然、健康、优质的，只为一份对极致美味的追求，用心做好每一份菜，是我们不变的宗旨。</span></p>
        <ul class="main-body-img">

            {% for prod in higher_rate_list %}
            <li><img src="{% static prod.image %}"></li>
            {% endfor %}
        </ul>
    </div>
</main>
<main>
    <ul class="main-submenu">
        <li><a href="#">午餐</a></li>
        <li><a href="#">晚餐</a></li>
        <li><a href="#">甜品</a></li>
        <li><a href="#">饮料</a></li>
    </ul>
    <ul class="main-submenu-info main-submenu-first">

        {% for prod in new_list %}
        <li><a href="#">
            <div class="food-name">
                <p>{{ prod.zh_name }}</p>
                <p>{{ prod.en_name }}</p>
            </div>
            <div class="food-price">
                <p>￥<span>{{ prod.price }}</span></p>
            </div>
            <div class="img-bg"></div>
            <img src="{% static prod.image %}"></a></li>
        {% endfor %}

    </ul>
    <a class="more" href="{% url 'product:product_list' %}#prod_list">MORE</a>
</main>
<main>
    <div>
        <div class="main-head">
            <p><span>美食资讯</span></p>
        </div>
    </div>
    <ul class="main-submenu main-submenu-second">
        <li><a href="#">最新新闻</a></li>
        <li><a href="#">餐厅新闻</a></li>
        <li><a href="#">美食热闻</a></li>
        <li><a href="#">甜品站</a></li>
    </ul>
    <ul class="main-submenu-info ">
        <li><a href="#">
            <div class="activity-duration">
                <img  src="images/activity-duration.png">
                <p>6-1日</p>
            </div>
            <img src="images/foodnewlist1.jpg">
            <h1 class="food-head">周末轻松制作美味甜品</h1>
            <p class="food-info">每个周末都抽出一个小时的时间来为自己做一份甜品，让周末的休闲充满制作甜蜜和品尝甜蜜的快乐。</p>
        </a></li>
        <li><a href="#">
            <div class="activity-duration">
                <img src="images/activity-duration.png">
                <p>6-1日</p>
            </div>
            <img  src="images/foodnewlist1.jpg">
            <h1 class="food-head">周末轻松制作美味甜品</h1>
            <p class="food-info">每个周末都抽出一个小时的时间来为自己做一份甜品，让周末的休闲充满制作甜蜜和品尝甜蜜的快乐。</p>
        </a></li>
        <li><a href="#">
            <div class="activity-duration">
                <img src="images/activity-duration.png">
                <p>6-1日</p>
            </div>
            <img src="images/foodnewlist1.jpg">
            <h1 class="food-head">周末轻松制作美味甜品</h1>
            <p class="food-info">每个周末都抽出一个小时的时间来为自己做一份甜品，让周末的休闲充满制作甜蜜和品尝甜蜜的快乐。</p>
        </a></li>

    </ul>
    <a class="more" href="#">MORE</a>
</main>
<main>

        <div class="main-head">
            <p><span>在线预定</span></p>
        </div>
        <div class="main-reserve">
            <form action="#" method="post" id="food-reserve">
                <ul>
                    <li>
                        <label for="username">姓名</label>
                        <input type="text" name="username" id="username">
                    </li>
                    <li>
                        <label for="phonenumber">电话号码</label>
                        <input type="text" name="phonenumber" id="phonenumber">
                    </li>
                    <li>
                        <label for="email">电子邮件</label>
                        <input type="text" name="email" id="email">
                    </li>
                    <li>
                        <label for="time">时间</label>
                        <input type="text" name="time" id="time">
                    </li>
                    <li>
                        <label for="numberofpeople">人数</label>
                        <input type="text" name="numberofpeople" id="numberofpeople">
                    </li>
                    <li>
                        <label for="date">日期</label>
                        <input type="text" name="date" id="date">
                    </li>
                    <li>
                        <label for="guestbook">留言</label>
                        <input type="text" name="guestbook" id="guestbook">
                    </li>
                </ul>
                <a class="reserve">预定</a>

            </form>
        </div>
</main>
{% endblock main %}


cate/templates/product/productlist.html

{% extends 'common/base.html' %}
{% load staticfiles %}
{% load prod_filters %}

{% block title %}
    <title>美食之家产品列表</title>
{% endblock title %}

{% block main %}
<main >

    <div>
        <div class="main-head">
            <p>
                <span>菜式欣赏</span>
            </p>
        </div>
    </div>
</main>
<main>
    <img class="mdbanner" src="{% static 'images/mdbanner.jpg' %}">
</main>
<main>
    <div class="main-body">
        <p><span>每一种食物来源都经过我们的精挑细选，关于食材我们只选最天然、健康、优质的，只为一份对极致美味的追求，用心做好每一份菜，是我们不变的宗旨。</span></p>
        <ul class="main-body-img">
            {% for prod in higher_rate_list %}
            <li><img src="{% static prod.image %}"></li>
            {% endfor %}

        </ul>
    </div>
</main>
<main>
    <ul class="main-submenu">
        <li><a href="#">午餐</a></li>
        <li><a href="#">晚餐</a></li>
        <li><a href="#">甜品</a></li>
        <li><a href="#">饮料</a></li>
    </ul>
    <a name="prod_list"></a>
    <ul class="main-submenu-info main-submenu-first">
        {% for prod in page.object_list %}
        <li><a href="#">
            <div class="food-name">
                <p>{{ prod.zh_name }}</p>
                <p>{{ prod.en_name }}/p>
            </div>
            <div class="food-price">
                <p>￥<span>{{ prod.price }}</span></p>
            </div>
            <div class="img-bg"></div>
            <img src="{% static prod.image %}"></a></li>
        {% endfor %}

    </ul>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if page.has_previous %}
            <li>
                <a href="{% url 'product:product_list' %}?page={{ page.previous_page_number }}#prod_list" aria-label="Next">
                    <span aria-hidden="true">上一页</span>
                </a>
            </li>
            {% endif %}

            {% for num in page.number|get_num_list:paginator.num_pages %}
                {% if num == page.number %}
                    <li><a href="{% url 'product:product_list' %}?page={{ num }}#prod_list" style="background-color:lightcoral">{{ num }}</a></li>
                    {% else %}
                    <li><a href="{% url 'product:product_list' %}?page={{ num }}#prod_list">{{ num }}</a></li>
                {% endif %}

            {% endfor %}

            {% if page.has_next %}
            <li>
                <a href="{% url 'product:product_list' %}?page={{ page.next_page_number }}#prod_list" aria-label="Next">
                    <span aria-hidden="true">下一页</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
</main>
<main>

    <div class="main-head">
        <p><span>在线预定</span></p>
    </div>
    <div class="main-reserve">
        <form action="#" method="post" id="food-reserve">
            <ul>
                <li>
                    <label for="username">姓名</label>
                    <input type="text" name="username" id="username">
                </li>
                <li>
                    <label for="phonenumber">电话号码</label>
                    <input type="text" name="phonenumber" id="phonenumber">
                </li>
                <li>
                    <label for="email">电子邮件</label>
                    <input type="text" name="email" id="email">
                </li>
                <li>
                    <label for="time">时间</label>
                    <input type="text" name="time" id="time">
                </li>
                <li>
                    <label for="numberofpeople">人数</label>
                    <input type="text" name="numberofpeople" id="numberofpeople">
                </li>
                <li>
                    <label for="date">日期</label>
                    <input type="text" name="date" id="date">
                </li>
                <li>
                    <label for="guestbook">留言</label>
                    <input type="text" name="guestbook" id="guestbook">
                </li>
            </ul>
            <a class="reserve">预定</a>

        </form>
    </div>

</main>

{% endblock main %}
